nodeLinker: node-modules

npmScopes:
  rajatsablok:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN}
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
