version: '3.4'
services:
  fampay-backend-assigment:
    depends_on:
      - redis-cache
      - mongo-db
    environment:
      NODE_ENV: development
      PORT: 3000
      YOUTUBE_API_KEYS: ${YOUTUBE_API_KEY_1},${YOUTUBE_API_KEY_2},${YOUTUBE_API_KEY_3}
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      REDIS_HOST: redis-cache
      DB_URI: mongodb://mongo-db:27017/local_db
    command: sh -c "node -r dotenv-safe/config build/src/index.js"
    image: fampay-backend-assigment
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
  mongo-db:
    image: mongo:5.0.9-focal
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./initMongo:/docker-entrypoint-initdb.d
  redis-cache:
    image: redis:7.0.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
